### ISSUE TITLE
Lossy month granularity + simpler implementation?

### ISSUE THREAD

**Issue by aseemk** [teepark/pqinterval#4]
Hi @teepark,

Thank you very much for this great library! I'm looking to use it, but one thing I noticed was that PostgreSQL maintains month-level granularity, but this library doesn't seem to.

Example: intervals of `1 month` vs. `30 days`, when added to a `Feb 1` date, smartly yield different results (as you'd expect) in PostgreSQL:

```sql
with intervals as (
  values (interval '1 month'), (interval '30 days')
)

, dates as (
  values ('2018-02-01'::date)
)

select date, interval, (date + interval)::date as next_date
from dates as dates(date)
join intervals as intervals(interval) on 1=1
```

```
    date    | interval | next_date  
------------+----------+------------
 2018-02-01 | 1 mon    | 2018-03-01
 2018-02-01 | 30 days  | 2018-03-03
```

But in this library, it looks like you parse `1 month` as 30 days, since `Interval` only stores integer years and days, not months:

https://github.com/teepark/pqinterval/blob/cebbdc68e7aa88ab33347a12e002a4fb821cc988/parse.go#L104-L105

https://github.com/teepark/pqinterval/blob/cebbdc68e7aa88ab33347a12e002a4fb821cc988/parse_test.go#L27-L34

Compare that to PostgreSQL's implementation which stores months, not years:

https://github.com/postgres/postgres/blob/30c66e77be1d890c3cca766259c0bec80bcac1b5/src/interfaces/ecpg/include/pgtypes_interval.h#L26-L30

And indeed, a signed 32-bit month value results in PostgreSQL's +/- 178M year range.

I also notice that PostgreSQL stores the rest of the interval in a single signed 64-bit integer, which supports the full microsecond-level precision as well:

https://github.com/postgres/postgres/blob/30c66e77be1d890c3cca766259c0bec80bcac1b5/src/interfaces/ecpg/pgtypeslib/interval.c#L975-L988

So out of curiosity, any reason this library doesn't take a similar approach? Let me know if I'm missing something, and thanks again!

**Comment by teepark** [comment]
Great find, thank you for this research @aseemk!

I definitely didn't do the in-depth plunge into postgresql internals that you have -- any conclusions I drew about the storage of intervals were based on the docs, and observing their behavior from a psql shell. It's also been a while and I don't recall the thought process that led to this particular memory layout (although it does support the full interval range in 96 bits instead of postgres's 128 on 64 bit architecture).

In looking at it now though, I don't think this loss of context really matters. There are two ways we might end up doing interval/timestamp arithmetic: in go or in postgres.

To do time arithmetic in go, we'd traverse `pqinterval.Interval -> pqinterval.Duration -> time.Duration` and end up in a time representation of a single `int64` as nanoseconds, throwing away the distinction between months of different lengths before we ever get to contextualize it by adding to a `time.Time`. So in short there was no way we were ever going to keep that distinction anyway.

To perform the same arithmetic in postgres, we'd actually first scan in a large number of days:
```
=> select '2018/05/03 12:34:56'::timestamp - '2017/06/13 19:18:17' as ival;
       ival
-------------------
 323 days 17:16:39
(1 row)
```
(this is a really helpful decision on postgresql's part to provide just days instead of X months and Y days, since it avoids this ambiguity)

When scanning that interval we'd [expand the days down into hours](https://github.com/teepark/pqinterval/blob/cebbdc68e7aa88ab33347a12e002a4fb821cc988/parse.go#L107-L108) rather than collapsing up into months. Then when we use that same `Interval` instance as a query parameter to do the time arithmetic in postgres, we'd — __oops: we'd [collapse the days into months](https://github.com/teepark/pqinterval/blob/cebbdc68e7aa88ab33347a12e002a4fb821cc988/interval.go#L105)__. That needs fixing, but it's just a matter of removing that one line -- pqinterval should follow postgres's example and avoid providing a number of months anywhere.

What do you think?

**Comment by aseemk** [comment]
Thanks for the quick and thorough response! Loved your "oops" thought process. =)

Your view makes a lot of sense. If subtracting two dates or times in PostgreSQL always returns day-level (and below) granularity, and this library doesn't mistakenly inflate that to month- or year-level granularity, that sounds good and should be robust.

I personally still have a use case for properly matching PostgreSQL's month-level granularity (to model schedules/frequencies like "once a month"), but you're right that if you never expect to read any intervals with month-level granularity (or higher), this library should function just fine. (Might be worth documenting that in the readme.)

Cheers!
